#!/bin/bash

set -euo pipefail
. /.functions

list_options()
{
	local VER="${1}"
	local A B C
	update-java-alternatives --list </dev/null 2>/dev/null | \
		awk '{ print $1 }' | \
		egrep "java-((0|[1-9][0-9]*)[.])?${VER}([.][0-9]+])?" | \
		sort
}

get_option()
{
	local VER="${1}"
	local OPTIONS=()
	readarray -t OPTIONS < <(list_options "${VER}")
	case ${#OPTIONS[@]} in
		0 ) echo "No Java alternatives were found for version ${VER}" ;;
		1 ) echo "${OPTIONS[0]}" ; return 0 ;;
		* ) echo "The Java alternative for version ${VER} had ${#OPTIONS[@]} options: [${OPTIONS[@]}]" ;;
	esac
	return 1
}

usage()
{
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [ -? | -h | --help ] [ version ]"
	echo -e ""
	echo -e "\tIf the version is not given as a parameter, an attempt"
	echo -e "\twill be made to read it from the environment variable"
	echo -e "\tALT_JAVA if it's defined and non-empty."
	echo -e ""
	exit 1
}

# If no parameter is given, we try to select the java
# version from the ALT_JAVA ENVVAR
[ ${#} -eq 0 ] && [ -v ALT_JAVA ] && [ -n "${ALT_JAVA}" ] && set -- "${ALT_JAVA}"

# If we're not being asked to set a Java version, we simply
# output the current one
[ ${#} -ne 1 ] && exec get-java

[ -n "${1}" ] || usage

# Some parameter QA
case "${1,,}" in
	"-?" | "-h" | "--help" ) usage ;;
esac

# Make sure we run as root
[ $(id -u) -eq 0 ] || exec sudo --non-interactive --preserve-env "PATH=${PATH}" "${0}" "${@}"

VER="${1}"

if [ "${VER,,}" == "auto" ] ; then
	update-java-alternatives --auto &>/dev/null || fail "Failed to re-set the Java alternative to auto mode"
	quit "Re-set the java alternative to automatic mode"
fi

OUT="$(get_option "${VER}")" || fail "${OUT}"
RESULT="$(update-java-alternatives --set "${OUT}" 2>&1)" || fail "Failed to configure the Java alternative to [${OUT}]  (number ${NUM}) (rc=${?}):\n${RESULT}"

JAVA="$(type -P java 2>/dev/null)" || fail "Java is not in the PATH!!"
JAVA="$(readlink -f "${JAVA}" 2>&1)" || fail "Failed to resolve the real location of the Java executable (rc=${?}): ${JAVA}"

# Java is actually in the directory ${JVM}/bin ... so find JVM!
JVM="$(dirname "$(dirname "${JAVA}")")"
JVM="$(readlink -f "${JVM}" 2>&1)" || fail "Failed to resolve the real location of the JAVA_HOME directory (rc=${?}): ${JVM}"

# Now we fix the ${JVM_BASE}/java and ${JVM_BASE}/jre symlinks
JVM_BASE="/usr/lib/jvm"
for SYM in java jre ; do
	SYM="${JVM_BASE}/${SYM}"
	if [ -e "${SYM}" ] ; then
		[ -h "${SYM}" ] || fail "The Java symbolic target [${SYM}] is not a symbolic link"
		OUT="$(rm -f "${SYM}" 2>&1)" || fail "Failed to clear the existing symbolic link at [${SYM}] (rc=${?}): ${OUT}"
	fi
	OUT="$(ln -sv "${JVM}" "${SYM}" 2>&1)" || fail "Failed to create the new symbolic link [${SYM}] -> [${JVM}] (rc=${?}): ${OUT}"
done

ok "Set Java to [${OUT}]"
