#!/bin/bash
echo "Setting the GIT identity"

#
# Set the username
#
[ -v GIT_USERNAME ] || GIT_USERNAME=""
[ -n "${GIT_USERNAME}" ] || GIT_USERNAME="svc.10.1.jenkins"
export GIT_USERNAME

/usr/bin/git config --global user.name "${GIT_USERNAME}"

#
# Set the e-mail address
#
[ -v GIT_USERMAIL ] || GIT_USERMAIL=""
[ -n "${GIT_USERMAIL}" ] || GIT_USERMAIL="${GIT_USERNAME}@armedia.com"
export GIT_USERMAIL

/usr/bin/git config --global user.email "${GIT_USERMAIL}"
