#!/bin/bash

[ -v DEBUG ] || DEBUG=""
[ -n "${DEBUG}" ] || DEBUG="false"

[ -e "${CONF_DIR}/.debug" ] && DEBUG="true"

case "${DEBUG,,}" in
	true | t | yes | y | enable | enabled | en | on )
		echo "CURRENT USER = $(id -a)"
		echo "***************************"
		echo "**** BEGIN ENVIRONMENT ****"
		echo "***************************"
		env
		echo "***************************"
		echo "***** END ENVIRONMENT *****"
		echo "***************************"
		DEBUG="true"
		;;

	* )	DEBUG="false" ;;
esac
export DEBUG

# Just so we don't return a non-0 value
true
